name: Open Baidu with Chrome and Selenium

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  open-baidu:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Chrome
        run: |
          # Update package lists
          sudo apt-get update
          
          # Install dependencies
          sudo apt-get install -y wget gnupg
          
          # Add Google Chrome's official repository
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' | sudo tee /etc/apt/sources.list.d/google-chrome.list
          
          # Update package lists again
          sudo apt-get update
          
          # Install Google Chrome
          sudo apt-get install -y google-chrome-stable

      - name: Set up ChromeDriver
        run: |
          # Determine the latest version of Chrome installed
          CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+\.\d+')
          echo "Installed Chrome version: $CHROME_VERSION"
          
          # Extract major version number
          MAJOR_VERSION=$(echo "$CHROME_VERSION" | cut -d'.' -f1)
          echo "Major Chrome version: $MAJOR_VERSION"
          
          # Download the corresponding ChromeDriver
          wget -N https://storage.googleapis.com/chrome-for-testing-public/131.0.6778.139/linux64/chromedriver-linux64.zip
          echo "Latest ChromeDriver version for Chrome $MAJOR_VERSION: $CHROMEDRIVER_VERSION"
          
          wget -N https://storage.googleapis.com/chrome-for-testing-public/131.0.6778.139/linux64/chromedriver-linux64.zip -P ~/
          
          # Unzip ChromeDriver
          unzip ~/chromedriver-linux64.zip -d ~/
          
          # Move ChromeDriver to PATH
          sudo mv -f ~/root/chromedriver /usr/local/bin/chromedriver
          sudo chown root:root /usr/local/bin/chromedriver
          sudo chmod 0755 /usr/local/bin/chromedriver
          
          # Verify installation
          chromedriver --version

      - name: Set up Python and Selenium
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Selenium
        run: |
          pip install selenium

      - name: Open Baidu
        run: |
          python - <<EOF
          from selenium import webdriver
          from selenium.webdriver.chrome.service import Service
          from selenium.webdriver.common.by import By
          from selenium.webdriver.chrome.options import Options
          import time

          # Set up Chrome options for headless mode
          chrome_options = Options()
          chrome_options.add_argument("--headless")
          chrome_options.add_argument("--no-sandbox")
          chrome_options.add_argument("--disable-dev-shm-usage")

          # Initialize the Chrome driver
          service = Service('/usr/local/bin/chromedriver')
          driver = webdriver.Chrome(service=service, options=chrome_options)

          # Open Baidu
          driver.get('https://www.baidu.com')

          # Print the title of the page
          print(f"Page Title: {driver.title}")

          # Wait for a few seconds
          time.sleep(5)

          # Close the browser
          driver.quit()
          EOF
