name: Open Website with Edge



    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install Microsoft Edge
      run: |
        curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
        sudo install -o root -g root -m 644 microsoft.gpg /etc/apt/trusted.gpg.d/
        sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main" > /etc/apt/sources.list.d/microsoft-edge-dev.list'
        rm microsoft.gpg
        sudo apt-get update
        sudo apt-get install -y microsoft-edge-stable

    - name: Determine Edge version
      id: edge_version
      run: |
        EDGE_VERSION=$(microsoft-edge --version | grep -oP '\d+\.\d+\.\d+\.\d+')
        echo "Edge version: $EDGE_VERSION"
        echo "::set-output name=edge-version::$EDGE_VERSION"

    - name: Download EdgeDriver
      id: download_edgedriver
      run: |
        EDGE_VERSION=${{ steps.edge_version.outputs.edge-version }}
        MAJOR_VERSION=$(echo "$EDGE_VERSION" | cut -d'.' -f1)
        wget -N https://msedgedriver.azureedge.net/LATEST_RELEASE_${MAJOR_VERSION} -O latest_release
        LATEST_EDGEDRIVER_VERSION=$(cat latest_release)
        wget -N https://msedgedriver.azureedge.net/${LATEST_EDGEDRIVER_VERSION}/edgedriver_linux64.zip -P ~/
        unzip ~/edgedriver_linux64.zip -d ~/

    - name: Move EdgeDriver to PATH
      run: |
        sudo mv ~/msedgedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/msedgedriver

    - name: Verify Edge installation
      run: microsoft-edge --version

    - name: Verify EdgeDriver installation
      run: msedgedriver --version

    - name: Install Selenium
      run: pip install selenium

    - name: Create and Run Open Website Script
      run: |
        cat <<EOF > open_website.py
import time
from selenium import webdriver
from selenium.webdriver.edge.service import Service
from selenium.webdriver.edge.options import Options
from selenium.common.exceptions import WebDriverException

# Configure Edge options for headless mode
edge_options = Options()
edge_options.add_argument("--headless")
edge_options.add_argument("--no-sandbox")
edge_options.add_argument("--disable-dev-shm-usage")

# Initialize the Edge WebDriver
try:
    service = Service('/usr/local/bin/msedgedriver')
    driver = webdriver.Edge(service=service, options=edge_options)
except WebDriverException as e:
    print(f"Failed to initialize WebDriver: {e}")
    exit(1)

# URL to open
url = "https://www.example.com"

try:
    driver.get(url)
    print(f"Opened page at {time.strftime('%Y-%m-%d %H:%M:%S')}")
    time.sleep(5)  # Wait for 5 seconds before closing the browser
except WebDriverException as e:
    print(f"Failed to load page: {e}")
finally:
    driver.quit()
EOF

        # Run the script
        python open_website.py



